on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

name: Render bookdown website

jobs:
  build-bookdown:
    if: | 
      !contains(github.event.commits[0].message, '[skip-renderbook]')
    
    runs-on: ubuntu-20.04
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # RENV_PATHS_ROOT: ~/.local/share/renv
      R_LIBS_USER: /home/runner/work/_temp/Library

    steps:
      - uses: actions/checkout@v3
      
      - uses: PredictiveEcology/actions/install-spatial-deps@main
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: 2
          use-public-rspm: false
          extra-repositories: 'https://predictiveecology.r-universe.dev/'
      
      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::bookdown
            any::cffr
            any::geodata
            any::ggplot2
            any::ggpubr
            any::htmlwidgets
            any::rcmdcheck
            any::rmarkdown
            any::png
            any::raster
            any::rsvg
            any::SpaDES.tools
            any::V8
      
      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX
      
      - name: Cache bookdown results
        uses: actions/cache@v3
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-
        
      - name: Render Bookdown
        run: |
          source("render.R", echo = TRUE)
        shell: Rscript {0}
      
      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
          
  update-citation:
    needs: build-bookdown
    
    runs-on: ubuntu-20.04
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::cffr
            any::V8
    
      - name: Update CITATION.cff
        run: |
          cffr::cff_write(dependencies = FALSE, authors_roles = c("aut", "cre", "ctb"))
        shell: Rscript {0}
          
      - name: Commit CITATION.cff update
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CITATION.cff
          git commit -m 'Update CITATION.cff' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

  
