on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

name: tutorial-check

jobs:
  tutorial-check:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: macOS-latest,   nosuggests: false, r: 'release'}
          # - {os: windows-latest, nosuggests: false, r: 'devel'}
          # - {os: windows-latest, nosuggests: false, r: 'release'}
          # - {os: windows-latest, nosuggests: false, r: 'oldrel'}
          - {os: ubuntu-20.04,   nosuggests: false, r: 'devel'}
          # - {os: ubuntu-20.04,   nosuggests: false, r: 'release'}
          # - {os: ubuntu-20.04,   nosuggests: true,  r: 'release'}
          # - {os: ubuntu-20.04,   nosuggests: false, r: 'oldrel'}

    env:
      _R_CHECK_DEPENDS_ONLY_: ${{ matrix.config.nosuggests }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      SPADES_USE_REQUIRE: false

    steps:
      - uses: actions/checkout@v3
          
      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: 8

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: PredictiveEcology/actions/install-spatial-deps@main
      
      - uses: r-lib/actions/setup-r@v2
        with:
          Ncpus: 2
          r-version: ${{ matrix.config.r }}
          use-public-rspm: false

      - name: Run tutorials - Part 1
        run: |
          source("Part1_DummyModel_test.R", echo = TRUE)
        shell: Rscript {0}

      - name: Run tutorials - Part 2
        run: |
          source("Part2_SDMs_test.R", echo = TRUE)
        shell: Rscript {0}
